// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function App(Props) {
  return React.createElement("div", undefined, "hello world");
}

var make = App;

exports.make = make;
/* react Not a pure module */
