// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Functor(P) {
  return P;
}

function f(x) {
  return x;
}

function g(x) {
  return x;
}

var M = {
  f: f,
  g: g
};

var L = {
  f: f
};

exports.Functor = Functor;
exports.M = M;
exports.L = L;
/* No side effect */
