// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function Make(Fst, Snd) {
  var make = function (f, s) {
    return [
            f,
            s
          ];
  };
  var print = function (param) {
    return "(" + (Curry._1(Fst.print, param[0]) + (", " + (Curry._1(Snd.print, param[1]) + ")")));
  };
  return {
          make: make,
          print: print
        };
}

exports.Make = Make;
/* No side effect */
