// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Make(RC) {
  var repeat = function (timesOpt, str) {
    var times = timesOpt !== undefined ? timesOpt : RC.count;
    if (times <= 0) {
      return "";
    } else {
      return str + repeat(times - 1 | 0, str);
    }
  };
  return {
          repeat: repeat
        };
}

exports.Make = Make;
/* No side effect */
