// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Invoice$PhantomTypes = require("./Invoice.bs.js");

var invoice = Invoice$PhantomTypes.make("Raphael", "persianturtle@gmail.com", new Date(), 15.0);

var invoice$1 = Invoice$PhantomTypes.discount(invoice, /* Ten */0);

console.log("invoice", invoice$1);

exports.invoice = invoice$1;
/* invoice Not a pure module */
