// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function make(name, email, date, total) {
  return {
          name: name,
          email: email,
          date: date,
          total: total
        };
}

function discount(invoice, discount$1) {
  var tmp;
  switch (discount$1) {
    case /* Ten */0 :
        tmp = 0.9;
        break;
    case /* Fifteen */1 :
        tmp = 0.85;
        break;
    case /* Twenty */2 :
        tmp = 0.8;
        break;
    
  }
  return {
          name: invoice.name,
          email: invoice.email,
          date: invoice.date,
          total: invoice.total * tmp
        };
}

exports.make = make;
exports.discount = discount;
/* No side effect */
