// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

Pervasives.print_string("Hello world!");

Pervasives.print_newline(undefined);

/*  Not a pure module */
