// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Log$ReasonmlDemoModules = require("./Log.bs.js");

Log$ReasonmlDemoModules.print(Log$ReasonmlDemoModules.logStr("everyone", Log$ReasonmlDemoModules.logStr("Hello", Log$ReasonmlDemoModules.make(undefined))));

/*  Not a pure module */
