// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Log$ReasonmlDemoModules = require("./Log.bs.js");

function logStrWithDate(str, log) {
  var dateStr = new Date().toISOString();
  return Log$ReasonmlDemoModules.logStr("[" + (dateStr + ("] " + str)), log);
}

var LogWithDate = {
  make: Log$ReasonmlDemoModules.make,
  logStr: Log$ReasonmlDemoModules.logStr,
  print: Log$ReasonmlDemoModules.print,
  logStrWithDate: logStrWithDate
};

Log$ReasonmlDemoModules.print(logStrWithDate("everyone", logStrWithDate("Hello", Log$ReasonmlDemoModules.make(undefined))));

exports.LogWithDate = LogWithDate;
/*  Not a pure module */
