// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var MathTools$ReasonmlDemoModules = require("./MathTools.bs.js");

Pervasives.print_string("Result: ");

Pervasives.print_int(MathTools$ReasonmlDemoModules.square(3));

Pervasives.print_newline(undefined);

/*  Not a pure module */
