// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function times(x, y) {
  return Math.imul(x, y);
}

function square(x) {
  return Math.imul(x, x);
}

exports.times = times;
exports.square = square;
/* No side effect */
