// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function $plus(x, y) {
  return Math.imul(x, y);
}

var DifferentPlus = {
  $plus: $plus
};

Pervasives.print_int(18);

exports.DifferentPlus = DifferentPlus;
/*  Not a pure module */
