// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var many = Math.max(1, 2);

var many2 = Math.max(1, 2, 3, 4);

console.log("max2 ", Math.max(1, 2));

console.log("max4 ", Math.max(1, 2, 3, 4));

console.log("many ", many);

console.log("many2 ", many2);

exports.many = many;
exports.many2 = many2;
/* many Not a pure module */
