// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var DynamicJs = require("./dynamic.js");

console.log("Hello, BuckleScript and Reason!");

console.log(DynamicJs.dynamic(42));

console.log(DynamicJs.dynamic("foo"));

function dynamic(prim) {
  return DynamicJs.dynamic(prim);
}

console.log(DynamicJs.dynamic(/* Int */Block.__(0, [1])));

exports.dynamic = dynamic;
/*  Not a pure module */
