// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Foo$PureReasonEnd = require("./Foo.bs.js");

console.log(Foo$PureReasonEnd.foo);

console.log(Foo$PureReasonEnd.y);

/*  Not a pure module */
