// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Invoice$PureReasonEnd = require("./Invoice.bs.js");

Invoice$PureReasonEnd.make("Raphael", "persianturtle@gmail.com", new Date(), 15.0);

var invoice = Invoice$PureReasonEnd.make("Raphael", "persianturtle@gmail.com", new Date(), 15.0);

console.log(invoice);

exports.invoice = invoice;
/*  Not a pure module */
