// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function foo(a, b) {
  return a + b | 0;
}

var Foo = {
  foo: foo
};

function foo$1(a, b) {
  return a + b | 0;
}

var Bar = {
  foo: foo$1
};

exports.Foo = Foo;
exports.Bar = Bar;
/* No side effect */
